window.THA_ONE_CONFIG = Object.freeze({
    apiOrigin: "",
    sessionEndpoint: "",
    profileEndpoint: "",
    profileUpdateEndpoint: "",
    addressesEndpoint: "",
    addressUpsertEndpoint: "",
    addressDeleteEndpoint: "",
    pincodeLookupEndpoint: "",
    reverseGeocodeEndpoint: "",
    serviceabilityEndpoint: "",
    logoutEndpoint: "",
    shoppingQuoteEndpoint: "",
    foodQuoteEndpoint: "",
    ordersEndpoint: "",
    experienceSelectEndpoint: "",
    shoppingCheckoutEndpoint: "",
    foodCheckoutEndpoint: "",
    paymentStartEndpoint: "",
    paymentVerifyEndpoint: "",
    paymentOrigin: "",
    orderStatusEndpoint: "",
    recommendationEndpoint: ""
});
