window.THA_ONE_CONFIG = Object.freeze({
    // Presentation builds only; disable for deployments that use real authentication and KYC.
    DEMO_MODE: true,
    apiOrigin: "",
    loginEndpoint: "",
    signupEndpoint: "",
    requestOtpEndpoint: "",
    verifyOtpEndpoint: "",
    passwordResetEndpoint: "",
    googleOAuthStartEndpoint: "",
    sessionEndpoint: "",
    profileEndpoint: "",
    profileUpdateEndpoint: "",
    addressesEndpoint: "",
    addressUpsertEndpoint: "",
    addressDeleteEndpoint: "",
    pincodeLookupEndpoint: "",
    reverseGeocodeEndpoint: "",
    serviceabilityEndpoint: "",
    logoutEndpoint: "",
    shoppingQuoteEndpoint: "",
    foodQuoteEndpoint: "",
    ordersEndpoint: "",
    experienceSelectEndpoint: "",
    shoppingCheckoutEndpoint: "",
    foodCheckoutEndpoint: "",
    paymentStartEndpoint: "",
    paymentVerifyEndpoint: "",
    paymentOrigin: "",
    orderStatusEndpoint: "",
    recommendationEndpoint: ""
});
