window.THA_ONE_FOOD = {
    categories: ["Pizza", "Burgers", "Chicken", "Chinese", "South Indian", "North Indian", "Healthy Food", "Desserts", "Beverages", "Snacks"],
    categoryImages: {
        Pizza: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=360&q=78",
        Burgers: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=360&q=78",
        Chicken: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=360&q=78",
        Chinese: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=360&q=78",
        "South Indian": "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=360&q=78",
        "North Indian": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=360&q=78",
        "Healthy Food": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=360&q=78",
        Desserts: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=360&q=78",
        Beverages: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=360&q=78",
        Snacks: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=360&q=78"
    },
    restaurants: [
        { id: "little-oven", name: "The Little Oven", cuisine: "Wood-fired pizza · Italian", rating: 4.8, time: "25–35 min", fee: 29, priceRange: "₹250 for two", offer: "20% off your first order", image: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=82", alt: "Fresh pizza with colorful toppings ready to share" },
        { id: "green-table", name: "The Green Table", cuisine: "Seasonal bowls · Healthy", rating: 4.7, time: "20–30 min", fee: 19, priceRange: "₹350 for two", offer: "Free drink with bowls", image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=82", alt: "Fresh salad bowl with greens and vegetables" },
        { id: "rice-and-spice", name: "Rice & Spice", cuisine: "South Indian · Homestyle", rating: 4.6, time: "30–40 min", fee: 25, priceRange: "₹300 for two", offer: "₹100 off orders over ₹399", image: "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=900&q=82", alt: "South Indian dosa served with chutneys" },
        { id: "bao-house", name: "Bao House", cuisine: "Chinese · Noodles · Dumplings", rating: 4.5, time: "25–35 min", fee: 22, priceRange: "₹400 for two", offer: "15% off on family meals", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=82", alt: "Steamed dumplings arranged on a plate" },
        { id: "charcoal-club", name: "Charcoal Club", cuisine: "North Indian · Grills · Wraps", rating: 4.7, time: "30–40 min", fee: 29, priceRange: "₹450 for two", offer: "Free side on orders over ₹499", image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=82", alt: "Grilled chicken served with fresh sides" },
        { id: "soft-serve", name: "Soft Serve Studio", cuisine: "Desserts · Ice cream", rating: 4.9, time: "15–25 min", fee: 15, priceRange: "₹200 for two", offer: "Buy 2 scoops, get 1 free", image: "https://images.unsplash.com/photo-1501446529957-6226bd447c46?auto=format&fit=crop&w=900&q=82", alt: "Colorful ice cream scoops in a waffle cone" },
        { id: "curry-leaf-kitchen", name: "Curry Leaf Kitchen", cuisine: "Biryani · North Indian", rating: 4.7, time: "30–40 min", fee: 24, priceRange: "₹380 for two", offer: "Free raita with biryani", image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=900&q=82", alt: "A bowl of fragrant biryani with fresh herbs" },
        { id: "wok-and-willow", name: "Wok & Willow", cuisine: "Chinese · Rice bowls", rating: 4.6, time: "25–35 min", fee: 20, priceRange: "₹320 for two", offer: "15% off family bowls", image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=82", alt: "Wok-fried rice with vegetables" },
        { id: "orchard-juice-bar", name: "Orchard Juice Bar", cuisine: "Fresh juice · Smoothies", rating: 4.8, time: "15–25 min", fee: 12, priceRange: "₹220 for two", offer: "Free seasonal cooler", image: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=900&q=82", alt: "Fresh fruit juice served chilled" }
    ],
    dishes: [
        { id: "margherita-pizza", restaurantId: "little-oven", name: "Garden Margherita", category: "Pizza", description: "Slow tomato, creamy mozzarella, basil and a crisp-edged sourdough base.", price: 329, rating: 4.8, image: "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=700&q=82", alt: "Freshly baked margherita pizza", vegetarian: true, options: ["Classic", "Extra cheese"] },
        { id: "smash-burger", restaurantId: "charcoal-club", name: "House Smash Burger", category: "Burgers", description: "A golden toasted bun, juicy grilled patty, crisp lettuce and house sauce.", price: 279, rating: 4.7, image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=82", alt: "Juicy burger with lettuce and tomato", vegetarian: false, options: ["Single", "Double"] },
        { id: "tandoori-chicken", restaurantId: "charcoal-club", name: "Charcoal Tandoori Chicken", category: "Chicken", description: "Smoky, slow-roasted chicken with fresh lemon and a side of mint yoghurt.", price: 389, rating: 4.6, image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=700&q=82", alt: "Tandoori chicken with fresh herbs", vegetarian: false, options: ["Half", "Full"] },
        { id: "sesame-noodles", restaurantId: "bao-house", name: "Sesame Garden Noodles", category: "Chinese", description: "Wok-tossed noodles with seasonal vegetables, sesame and a little ginger.", price: 249, rating: 4.5, image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=700&q=82", alt: "Noodles tossed with vegetables and sesame", vegetarian: true, options: ["Mild", "Spicy"] },
        { id: "masala-dosa", restaurantId: "rice-and-spice", name: "Crisp Masala Dosa", category: "South Indian", description: "A delicate golden dosa filled with spiced potato, served with sambar and chutneys.", price: 189, rating: 4.8, image: "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=700&q=82", alt: "Crisp dosa served with chutneys", vegetarian: true, options: ["Regular", "Ghee roast"] },
        { id: "paneer-tikka-wrap", restaurantId: "charcoal-club", name: "Paneer Tikka Wrap", category: "North Indian", description: "Charred paneer tikka, crisp onion and mint yoghurt wrapped in a warm flatbread.", price: 269, rating: 4.6, image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=700&q=82", alt: "North Indian paneer curry with fresh herbs", vegetarian: true, options: ["Regular", "Extra paneer"] },
        { id: "green-bowl", restaurantId: "green-table", name: "Everyday Green Bowl", category: "Healthy Food", description: "Avocado, crisp greens, roasted chickpeas and a bright lemon-herb dressing.", price: 319, rating: 4.7, image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=82", alt: "Fresh green bowl with vegetables", vegetarian: true, options: ["Regular", "Add tofu"] },
        { id: "mango-cheesecake", restaurantId: "soft-serve", name: "Mango Cloud Cheesecake", category: "Desserts", description: "A light, creamy cheesecake with ripe mango and a crisp biscuit base.", price: 229, rating: 4.9, image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=82", alt: "Creamy cake decorated with fruit", vegetarian: true, options: ["Slice", "Two slices"] },
        { id: "cold-coffee", restaurantId: "soft-serve", name: "Slow Cold Coffee", category: "Beverages", description: "Slow-steeped coffee over ice with a smooth pour of milk.", price: 149, rating: 4.6, image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=700&q=82", alt: "Iced coffee in a clear glass", vegetarian: true, options: ["Regular", "Large"] },
        { id: "chicken-biryani", restaurantId: "curry-leaf-kitchen", name: "Dum Chicken Biryani", category: "North Indian", description: "Fragrant basmati rice layered with slow-cooked chicken, warm spices and herbs.", price: 349, rating: 4.8, image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=700&q=82", alt: "Chicken biryani with fresh herbs and spices", vegetarian: false, options: ["Regular", "Family"] },
        { id: "vegetable-fried-rice", restaurantId: "wok-and-willow", name: "Garden Vegetable Fried Rice", category: "Chinese", description: "Wok-tossed rice with crisp seasonal vegetables, scallion and sesame.", price: 229, rating: 4.6, image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=700&q=82", alt: "Vegetable fried rice in a bowl", vegetarian: true, options: ["Mild", "Chilli garlic"] },
        { id: "chocolate-fudge-cake", restaurantId: "soft-serve", name: "Chocolate Fudge Cake", category: "Desserts", description: "Soft chocolate sponge, dark ganache and a little flaky chocolate on top.", price: 199, rating: 4.8, image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=82", alt: "Chocolate layer cake with rich frosting", vegetarian: true, options: ["Slice", "Two slices"] },
        { id: "mango-orange-juice", restaurantId: "orchard-juice-bar", name: "Mango & Orange Cooler", category: "Beverages", description: "Fresh mango and orange blended over ice for a bright afternoon drink.", price: 129, rating: 4.7, image: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=700&q=82", alt: "Freshly prepared fruit juice in a glass", vegetarian: true, options: ["Regular", "Large"] },
        { id: "crisp-veg-samosa", restaurantId: "curry-leaf-kitchen", name: "Crisp Potato Samosa", category: "Snacks", description: "Golden pastry filled with spiced potato, served with tamarind chutney.", price: 99, rating: 4.5, image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=82", alt: "Golden samosas served with chutney", vegetarian: true, options: ["Two pieces", "Four pieces"] }
    ]
};
