window.THA_ONE_PRODUCTS = [
    {
        id: "arc-headphones",
        name: "Arc wireless headphones",
        category: "Electronics",
        price: 6490,
        originalPrice: 8990,
        rating: 4.8,
        reviews: 328,
        badge: "Bestseller",
        description: "Rich, balanced sound meets a soft, all-day fit. Arc headphones bring your playlists, calls and quiet moments into focus with long-lasting comfort and simple controls.",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=82",
        gallery: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=82", "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=82"],
        alt: "Over-ear headphones in a warm studio setting",
        deals: true,
        variants: ["Midnight", "Cloud", "Olive"]
    },
    {
        id: "stride-runners",
        name: "Stride everyday runners",
        category: "Sports",
        price: 3490,
        originalPrice: 4990,
        rating: 4.7,
        reviews: 214,
        badge: "Just in",
        description: "A lightweight knit upper and cushioned sole make Stride an easy choice for early starts, city walks and everything that happens between.",
        image: "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=900&q=82",
        alt: "A collection of everyday shoes arranged together",
        deals: true,
        variants: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]
    },
    {
        id: "halo-watch",
        name: "Halo everyday smartwatch",
        category: "Electronics",
        price: 7290,
        originalPrice: 9990,
        rating: 4.6,
        reviews: 176,
        badge: "Member favourite",
        description: "A bright, clear display, thoughtful activity tracking and a comfortable strap keep your day in view without getting in the way.",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=82",
        gallery: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=82", "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=900&q=82"],
        alt: "Minimal wristwatch photographed on a light background",
        deals: true,
        variants: ["Black", "Silver", "Sage"]
    },
    {
        id: "daylight-lamp",
        name: "Daylight ceramic table lamp",
        category: "Home",
        price: 4290,
        originalPrice: 5490,
        rating: 4.9,
        reviews: 92,
        badge: "Small-batch",
        description: "A softly sculpted ceramic base and warm linen shade make this little lamp feel right at home on a bedside table, reading nook or work desk.",
        image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=82",
        alt: "Warm modern table lamp in a calm interior",
        deals: false,
        variants: ["Chalk", "Moss"]
    },
    {
        id: "everyday-crossbody",
        name: "Everyday city backpack",
        category: "Fashion",
        price: 2890,
        originalPrice: 3790,
        rating: 4.5,
        reviews: 143,
        badge: "Easy carry",
        description: "A compact shape with room for the things you reach for most. Adjustable, lightweight and ready for a quick coffee or a full day out.",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=82",
        alt: "A simple navy everyday backpack against a light background",
        deals: true,
        variants: ["Cognac", "Black", "Stone"]
    },
    {
        id: "daily-serum",
        name: "Purely daily face serum",
        category: "Beauty",
        price: 950,
        originalPrice: 1290,
        rating: 4.7,
        reviews: 289,
        badge: "Clean routine",
        description: "A lightweight daily serum made for a simple, comfortable routine. Smooths on easily and layers well under your everyday moisturiser.",
        image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=900&q=82",
        alt: "Minimal skincare bottles arranged on a soft neutral surface",
        deals: true,
        variants: ["30 ml", "50 ml"]
    },
    {
        id: "pocket-phone",
        name: "Pocket Pro smartphone",
        category: "Mobiles",
        price: 21990,
        originalPrice: 25990,
        rating: 4.6,
        reviews: 401,
        badge: "Limited offer",
        description: "A bright edge-to-edge screen, a dependable all-day battery and a capable camera in a comfortable, pocket-friendly form.",
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=82",
        gallery: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=82", "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=82"],
        alt: "Modern smartphone photographed from the back",
        deals: true,
        variants: ["128 GB", "256 GB"]
    },
    {
        id: "hydra-bottle",
        name: "Hydra steel bottle",
        category: "Accessories",
        price: 790,
        originalPrice: 1090,
        rating: 4.8,
        reviews: 517,
        badge: "Everyday essential",
        description: "A double-wall insulated steel bottle that keeps your drink close from the first commute to the last stretch of the day.",
        image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=82",
        alt: "Reusable stainless steel water bottle",
        deals: true,
        variants: ["Forest", "Cream", "Coral"]
    },
    {
        id: "pour-over-set",
        name: "Slow morning pour-over set",
        category: "Grocery",
        price: 1690,
        originalPrice: 2190,
        rating: 4.9,
        reviews: 116,
        badge: "A little ritual",
        description: "A thoughtful starter set for an unhurried cup. Pair the reusable brewer with your favourite ground coffee and a quiet ten minutes.",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=82",
        alt: "Freshly brewed coffee and coffee-making accessories",
        deals: false,
        variants: ["Single cup", "Two cup"]
    },
    {
        id: "cloud-knit-tee",
        name: "Cloud knit everyday tee",
        category: "Fashion",
        price: 1290,
        originalPrice: 1790,
        rating: 4.4,
        reviews: 87,
        badge: "Soft by design",
        description: "An easy, breathable knit with a relaxed shape. Made to be the first thing you reach for on a slow morning or a busy one.",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=82",
        alt: "Classic white cotton t-shirt on a neutral background",
        deals: false,
        variants: ["XS", "S", "M", "L", "XL"]
    },
    {
        id: "weekend-sunglasses",
        name: "Weekend acetate sunglasses",
        category: "Accessories",
        price: 1890,
        originalPrice: 2490,
        rating: 4.5,
        reviews: 64,
        badge: "Sun-ready",
        description: "A light, easy frame with a timeless silhouette and comfortable fit. Keep them by the door for bright days and open windows.",
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=82",
        alt: "Dark sunglasses in a bright outdoor setting",
        deals: false,
        variants: ["Tortoise", "Black"]
    },
    {
        id: "move-speaker",
        name: "Move portable speaker",
        category: "Electronics",
        price: 2490,
        originalPrice: 3290,
        rating: 4.6,
        reviews: 105,
        badge: "Take it outside",
        description: "Pocket-sized sound with simple pairing and a grippy finish. Bring a little background music to picnics, kitchen prep and slow weekends.",
        image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=82",
        alt: "Compact portable speaker on a clean surface",
        deals: false,
        variants: ["Charcoal", "Sage"]
    },
    {
        id: "northstar-laptop",
        name: "Northstar everyday laptop",
        category: "Laptops",
        price: 58990,
        originalPrice: 69990,
        rating: 4.7,
        reviews: 148,
        badge: "Workday favourite",
        description: "A balanced laptop for thoughtful work, video calls and everyday creative projects.",
        image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=82",
        alt: "Slim laptop open on a clean desk",
        deals: true,
        variants: ["8 GB · 256 GB", "16 GB · 512 GB"]
    },
    {
        id: "airloop-earbuds",
        name: "Airloop wireless earbuds",
        category: "Earbuds & Headphones",
        price: 2990,
        originalPrice: 3990,
        rating: 4.6,
        reviews: 203,
        badge: "Clear calls",
        description: "Compact wireless earbuds with a pocket case and a comfortable all-day fit.",
        image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=82",
        alt: "Wireless earbuds and charging case",
        deals: true,
        variants: ["Ivory", "Graphite"]
    },
    {
        id: "halo-active-watch",
        name: "Halo active smartwatch",
        category: "Smart Watches",
        price: 7990,
        originalPrice: 10490,
        rating: 4.7,
        reviews: 187,
        badge: "New colour",
        description: "A bright display and useful activity tools in a lightweight, everyday watch.",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=82",
        alt: "Minimal smartwatch photographed on a light background",
        deals: true,
        variants: ["Black", "Sage"]
    },
    {
        id: "canvas-overshirt",
        name: "Canvas weekend overshirt",
        category: "Fashion",
        price: 2490,
        originalPrice: 3290,
        rating: 4.5,
        reviews: 94,
        badge: "Easy layer",
        description: "A relaxed cotton layer made for cool mornings and slow weekend plans.",
        image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=82",
        alt: "Contemporary everyday fashion in natural light",
        deals: false,
        variants: ["S", "M", "L", "XL"]
    },
    {
        id: "stride-court-shoes",
        name: "Stride court sneakers",
        category: "Footwear",
        price: 3790,
        originalPrice: 4990,
        rating: 4.6,
        reviews: 121,
        badge: "City ready",
        description: "A versatile low-profile sneaker with a soft insole and sturdy everyday sole.",
        image: "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=900&q=82",
        alt: "Everyday footwear arranged against a neutral background",
        deals: true,
        variants: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]
    },
    {
        id: "field-notes-backpack",
        name: "Field Notes commuter backpack",
        category: "Bags",
        price: 3190,
        originalPrice: 4290,
        rating: 4.8,
        reviews: 162,
        badge: "Room for the day",
        description: "A practical, light carry with a padded laptop sleeve and easy-access pockets.",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=82",
        alt: "Everyday backpack photographed against a clean background",
        deals: false,
        variants: ["Olive", "Black"]
    },
    {
        id: "frame-mirrorless-camera",
        name: "Frame mirrorless camera",
        category: "Cameras",
        price: 45990,
        originalPrice: 52990,
        rating: 4.7,
        reviews: 73,
        badge: "Creator pick",
        description: "A compact camera kit for weekend walks, family moments and first creative projects.",
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=82",
        alt: "Digital camera ready for a day of photography",
        deals: true,
        variants: ["Body only", "With 18–55 mm lens"]
    },
    {
        id: "breeze-air-purifier",
        name: "Breeze compact air purifier",
        category: "Home Appliances",
        price: 8990,
        originalPrice: 10990,
        rating: 4.6,
        reviews: 88,
        badge: "A calmer home",
        description: "A compact room purifier with simple controls and a quiet night setting.",
        image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=82",
        alt: "Bright modern home with useful appliance details",
        deals: false,
        variants: ["White", "Stone"]
    },
    {
        id: "pixel-play-controller",
        name: "Pixel Play wireless controller",
        category: "Gaming",
        price: 3490,
        originalPrice: 4490,
        rating: 4.5,
        reviews: 136,
        badge: "Ready to play",
        description: "A responsive wireless controller with a comfortable grip for relaxed game nights.",
        image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=82",
        alt: "Gaming console and controller in a home entertainment setup",
        deals: true,
        variants: ["Cloud", "Midnight"]
    }
];

window.THA_ONE_SHOPPING_CATEGORIES = [
    { name: "Mobiles", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=480&q=78", alt: "Modern smartphone" },
    { name: "Laptops", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=480&q=78", alt: "Laptop on a desk" },
    { name: "Earbuds & Headphones", image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=480&q=78", alt: "Wireless earbuds" },
    { name: "Smart Watches", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=480&q=78", alt: "Everyday wristwatch" },
    { name: "Fashion", image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=480&q=78", alt: "Fashion collection" },
    { name: "Footwear", image: "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=480&q=78", alt: "Everyday shoes" },
    { name: "Bags", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=480&q=78", alt: "Commuter backpack" },
    { name: "Cameras", image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=480&q=78", alt: "Digital camera" },
    { name: "Home Appliances", image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=480&q=78", alt: "Modern home interior" },
    { name: "Beauty", image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=480&q=78", alt: "Skincare products" },
    { name: "Gaming", image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=480&q=78", alt: "Gaming controller and console" },
    { name: "Sports", image: "https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=480&q=78", alt: "Sports footwear" }
];
